name = "urgency-stock-timer-pro"
client_id = ""
application_url = ""
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = []

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
