# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2027c549d25100032acc19fa2e141752"
name = "Urgency Stock Time Pro"
application_url = "https://localhost"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = false
